name: GREY WATSON
favicon: null
layout_spectrum: 0.13107
typography_spectrum: 0.3024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.49799175933003426
  saturation: 0.7878745598718524
  rhythmicContrast: 0
purpose: []
